"""empty message

Revision ID: 3db6e557f33b
Revises: 
Create Date: 2026-08-25 21:28:45.108236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db6e557f33b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_units_parent_id'), table_name='organization_units')
    op.drop_index(op.f('ix_organization_units_unit_type'), table_name='organization_units')
    op.drop_constraint(op.f('organization_units_parent_id_fkey'), 'organization_units', type_='foreignkey')
    op.create_foreign_key(None, 'organization_units', 'organization_units', ['parent_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_users_member_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_member_id'), 'users', ['member_id'], unique=False)
    op.drop_constraint(None, 'organization_units', type_='foreignkey')
    op.create_foreign_key(op.f('organization_units_parent_id_fkey'), 'organization_units', 'organization_units', ['parent_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_organization_units_unit_type'), 'organization_units', ['unit_type'], unique=False)
    op.create_index(op.f('ix_organization_units_parent_id'), 'organization_units', ['parent_id'], unique=False)
    # ### end Alembic commands ###
